// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Telemetry

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AhuData struct {
	_tab flatbuffers.Table
}

func GetRootAsAhuData(buf []byte, offset flatbuffers.UOffsetT) *AhuData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AhuData{}
	x.Init(buf, n+offset)
	return x
}

func FinishAhuDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAhuData(buf []byte, offset flatbuffers.UOffsetT) *AhuData {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AhuData{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAhuDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AhuData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AhuData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AhuData) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AhuData) SupplyTemp() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *AhuData) MutateSupplyTemp(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *AhuData) Pressure() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *AhuData) MutatePressure(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *AhuData) Status() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AhuData) Mode() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AhuDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func AhuDataAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func AhuDataAddSupplyTemp(builder *flatbuffers.Builder, supplyTemp float32) {
	builder.PrependFloat32Slot(1, supplyTemp, 0.0)
}
func AhuDataAddPressure(builder *flatbuffers.Builder, pressure float32) {
	builder.PrependFloat32Slot(2, pressure, 0.0)
}
func AhuDataAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(status), 0)
}
func AhuDataAddMode(builder *flatbuffers.Builder, mode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(mode), 0)
}
func AhuDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
