// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Telemetry

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GlobalData struct {
	_tab flatbuffers.Table
}

func GetRootAsGlobalData(buf []byte, offset flatbuffers.UOffsetT) *GlobalData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GlobalData{}
	x.Init(buf, n+offset)
	return x
}

func FinishGlobalDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGlobalData(buf []byte, offset flatbuffers.UOffsetT) *GlobalData {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GlobalData{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGlobalDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GlobalData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GlobalData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GlobalData) BuildingLoadMw() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *GlobalData) MutateBuildingLoadMw(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *GlobalData) SystemHealth() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *GlobalData) MutateSystemHealth(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *GlobalData) TotalOccupants() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GlobalData) MutateTotalOccupants(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *GlobalData) CoolingOutputMw() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *GlobalData) MutateCoolingOutputMw(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *GlobalData) PlantCop() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *GlobalData) MutatePlantCop(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *GlobalData) EnergySavedMw() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *GlobalData) MutateEnergySavedMw(n float32) bool {
	return rcv._tab.MutateFloat32Slot(14, n)
}

func GlobalDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func GlobalDataAddBuildingLoadMw(builder *flatbuffers.Builder, buildingLoadMw float32) {
	builder.PrependFloat32Slot(0, buildingLoadMw, 0.0)
}
func GlobalDataAddSystemHealth(builder *flatbuffers.Builder, systemHealth float32) {
	builder.PrependFloat32Slot(1, systemHealth, 0.0)
}
func GlobalDataAddTotalOccupants(builder *flatbuffers.Builder, totalOccupants int32) {
	builder.PrependInt32Slot(2, totalOccupants, 0)
}
func GlobalDataAddCoolingOutputMw(builder *flatbuffers.Builder, coolingOutputMw float32) {
	builder.PrependFloat32Slot(3, coolingOutputMw, 0.0)
}
func GlobalDataAddPlantCop(builder *flatbuffers.Builder, plantCop float32) {
	builder.PrependFloat32Slot(4, plantCop, 0.0)
}
func GlobalDataAddEnergySavedMw(builder *flatbuffers.Builder, energySavedMw float32) {
	builder.PrependFloat32Slot(5, energySavedMw, 0.0)
}
func GlobalDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
