// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Telemetry

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ZoneData struct {
	_tab flatbuffers.Table
}

func GetRootAsZoneData(buf []byte, offset flatbuffers.UOffsetT) *ZoneData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ZoneData{}
	x.Init(buf, n+offset)
	return x
}

func FinishZoneDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsZoneData(buf []byte, offset flatbuffers.UOffsetT) *ZoneData {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ZoneData{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedZoneDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ZoneData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ZoneData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ZoneData) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ZoneData) Temp() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ZoneData) MutateTemp(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *ZoneData) Occupants() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ZoneData) MutateOccupants(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *ZoneData) Load() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ZoneData) MutateLoad(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func ZoneDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ZoneDataAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func ZoneDataAddTemp(builder *flatbuffers.Builder, temp float32) {
	builder.PrependFloat32Slot(1, temp, 0.0)
}
func ZoneDataAddOccupants(builder *flatbuffers.Builder, occupants int32) {
	builder.PrependInt32Slot(2, occupants, 0)
}
func ZoneDataAddLoad(builder *flatbuffers.Builder, load float32) {
	builder.PrependFloat32Slot(3, load, 0.0)
}
func ZoneDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
