#!/usr/bin/env bash
# Mint MQTT credentials for the three ECON roles and write the files the broker needs.
#
# Run once, before the first `docker compose up`. Re-running rotates every password.
#
#   ./setup-mqtt-auth.sh
#
# Writes:
#   mosquitto/passwd   hashed credentials, mounted read-only into the broker
#   .env               the plaintext the engine and nodes authenticate with
#
# Both are gitignored. .env is the file you copy secrets out of when flashing firmware;
# it is not the file you commit, paste into an issue, or screenshot.
set -euo pipefail
cd "$(dirname "$0")"

PASSWD=mosquitto/passwd
ENVFILE=.env

if [ -f "$PASSWD" ] && [ "${1:-}" != "--rotate" ]; then
  echo "$PASSWD already exists. Re-run with --rotate to replace every password."
  exit 0
fi

# Prefer the broker image's own mosquitto_passwd so the hash format always matches the
# broker that will read it, rather than whatever happens to be installed on this laptop.
gen() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32; }

ENGINE_PW=$(gen); NODE_PW=$(gen); GATEWAY_PW=$(gen)

rm -f "$PASSWD"; : > "$PASSWD"
if command -v mosquitto_passwd >/dev/null 2>&1; then
  RUN() { mosquitto_passwd "$@"; }
elif command -v docker >/dev/null 2>&1; then
  echo "mosquitto_passwd not installed locally — using the eclipse-mosquitto image."
  RUN() { docker run --rm -i -v "$PWD/mosquitto:/m" eclipse-mosquitto:2 mosquitto_passwd "${@/mosquitto\//\/m\/}"; }
else
  echo "ERROR: need either mosquitto_passwd or docker to hash the passwords." >&2
  exit 1
fi

RUN -b "$PASSWD" econ-engine  "$ENGINE_PW"
RUN -b "$PASSWD" econ-node    "$NODE_PW"
RUN -b "$PASSWD" econ-gateway "$GATEWAY_PW"
chmod 600 "$PASSWD"

# Preserve any admin token already chosen; generate one if there is none, because an
# engine deployed with an empty token accepts commands from anyone who can reach it.
ADMIN=$( [ -f "$ENVFILE" ] && grep -E '^ECON_ADMIN_TOKEN=' "$ENVFILE" | cut -d= -f2- || true )
[ -n "${ADMIN:-}" ] || ADMIN=$(gen)

cat > "$ENVFILE" <<ENV
# Generated by setup-mqtt-auth.sh. Gitignored. Treat as the building's keys.
ECON_ADMIN_TOKEN=$ADMIN
MQTT_USERNAME=econ-engine
MQTT_PASSWORD=$ENGINE_PW
ENV
chmod 600 "$ENVFILE"

cat <<MSG

MQTT credentials written.

  broker users   econ-engine / econ-node / econ-gateway   (mosquitto/passwd)
  engine + admin token                                    (.env, read by docker compose)

Flash the NODE credentials into firmware and paste them into the Python nodes:

  MQTT_USER=econ-node
  MQTT_PASS=$NODE_PW

Gateway (edge/raspberry_pi/gateway.py):

  MQTT_USER=econ-gateway
  MQTT_PASS=$GATEWAY_PW

Operator dashboard token (paste into the dashboard once per browser):

  $ADMIN

This is the only time these are printed. Both files are chmod 600 and gitignored.
MSG
