[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_unflags = -std=gnu++11
build_flags = -std=gnu++17 -DUSE_IR_AC=1 -DIR_AC_PROTOCOL=ELECTRA_AC -DUSE_SHT30=1 -DUSE_CO2=1 -DUSE_PLUG=1 -DUSE_STRIP=1 -DUSE_PIR=1
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.3
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    crankyoldgit/IRremoteESP8266 @ ^2.8.6
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0
