// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class AhuData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AhuData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAhuData(bb:flatbuffers.ByteBuffer, obj?:AhuData):AhuData {
  return (obj || new AhuData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAhuData(bb:flatbuffers.ByteBuffer, obj?:AhuData):AhuData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AhuData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

supplyTemp():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

pressure():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

status():string|null
status(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
status(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

mode():string|null
mode(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
mode(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startAhuData(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addSupplyTemp(builder:flatbuffers.Builder, supplyTemp:number) {
  builder.addFieldFloat32(1, supplyTemp, 0.0);
}

static addPressure(builder:flatbuffers.Builder, pressure:number) {
  builder.addFieldFloat32(2, pressure, 0.0);
}

static addStatus(builder:flatbuffers.Builder, statusOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, statusOffset, 0);
}

static addMode(builder:flatbuffers.Builder, modeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, modeOffset, 0);
}

static endAhuData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAhuData(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, supplyTemp:number, pressure:number, statusOffset:flatbuffers.Offset, modeOffset:flatbuffers.Offset):flatbuffers.Offset {
  AhuData.startAhuData(builder);
  AhuData.addId(builder, idOffset);
  AhuData.addSupplyTemp(builder, supplyTemp);
  AhuData.addPressure(builder, pressure);
  AhuData.addStatus(builder, statusOffset);
  AhuData.addMode(builder, modeOffset);
  return AhuData.endAhuData(builder);
}
}
