// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GlobalData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GlobalData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGlobalData(bb:flatbuffers.ByteBuffer, obj?:GlobalData):GlobalData {
  return (obj || new GlobalData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGlobalData(bb:flatbuffers.ByteBuffer, obj?:GlobalData):GlobalData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GlobalData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

buildingLoadMw():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

systemHealth():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

totalOccupants():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

coolingOutputMw():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

plantCop():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

energySavedMw():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

bessDischargeMw():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

bessSocPct():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

avgCo2():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startGlobalData(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addBuildingLoadMw(builder:flatbuffers.Builder, buildingLoadMw:number) {
  builder.addFieldFloat32(0, buildingLoadMw, 0.0);
}

static addSystemHealth(builder:flatbuffers.Builder, systemHealth:number) {
  builder.addFieldFloat32(1, systemHealth, 0.0);
}

static addTotalOccupants(builder:flatbuffers.Builder, totalOccupants:number) {
  builder.addFieldInt32(2, totalOccupants, 0);
}

static addCoolingOutputMw(builder:flatbuffers.Builder, coolingOutputMw:number) {
  builder.addFieldFloat32(3, coolingOutputMw, 0.0);
}

static addPlantCop(builder:flatbuffers.Builder, plantCop:number) {
  builder.addFieldFloat32(4, plantCop, 0.0);
}

static addEnergySavedMw(builder:flatbuffers.Builder, energySavedMw:number) {
  builder.addFieldFloat32(5, energySavedMw, 0.0);
}

static addBessDischargeMw(builder:flatbuffers.Builder, bessDischargeMw:number) {
  builder.addFieldFloat32(6, bessDischargeMw, 0.0);
}

static addBessSocPct(builder:flatbuffers.Builder, bessSocPct:number) {
  builder.addFieldFloat32(7, bessSocPct, 0.0);
}

static addAvgCo2(builder:flatbuffers.Builder, avgCo2:number) {
  builder.addFieldFloat32(8, avgCo2, 0.0);
}

static endGlobalData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGlobalData(builder:flatbuffers.Builder, buildingLoadMw:number, systemHealth:number, totalOccupants:number, coolingOutputMw:number, plantCop:number, energySavedMw:number, bessDischargeMw:number, bessSocPct:number, avgCo2:number):flatbuffers.Offset {
  GlobalData.startGlobalData(builder);
  GlobalData.addBuildingLoadMw(builder, buildingLoadMw);
  GlobalData.addSystemHealth(builder, systemHealth);
  GlobalData.addTotalOccupants(builder, totalOccupants);
  GlobalData.addCoolingOutputMw(builder, coolingOutputMw);
  GlobalData.addPlantCop(builder, plantCop);
  GlobalData.addEnergySavedMw(builder, energySavedMw);
  GlobalData.addBessDischargeMw(builder, bessDischargeMw);
  GlobalData.addBessSocPct(builder, bessSocPct);
  GlobalData.addAvgCo2(builder, avgCo2);
  return GlobalData.endGlobalData(builder);
}
}
