// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AhuData } from '../telemetry/ahu-data.js';
import { GlobalData } from '../telemetry/global-data.js';
import { VavData } from '../telemetry/vav-data.js';
import { ZoneData } from '../telemetry/zone-data.js';


export class SimState {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SimState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSimState(bb:flatbuffers.ByteBuffer, obj?:SimState):SimState {
  return (obj || new SimState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSimState(bb:flatbuffers.ByteBuffer, obj?:SimState):SimState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SimState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

zones(index: number, obj?:ZoneData):ZoneData|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ZoneData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

zonesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

vavs(index: number, obj?:VavData):VavData|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new VavData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

vavsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

ahus(index: number, obj?:AhuData):AhuData|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new AhuData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

ahusLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

global(obj?:GlobalData):GlobalData|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new GlobalData()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startSimState(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(0, timestamp, BigInt('0'));
}

static addZones(builder:flatbuffers.Builder, zonesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, zonesOffset, 0);
}

static createZonesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startZonesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addVavs(builder:flatbuffers.Builder, vavsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, vavsOffset, 0);
}

static createVavsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startVavsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addAhus(builder:flatbuffers.Builder, ahusOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, ahusOffset, 0);
}

static createAhusVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startAhusVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addGlobal(builder:flatbuffers.Builder, globalOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, globalOffset, 0);
}

static endSimState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishSimStateBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedSimStateBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

}
