// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class VavData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VavData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVavData(bb:flatbuffers.ByteBuffer, obj?:VavData):VavData {
  return (obj || new VavData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVavData(bb:flatbuffers.ByteBuffer, obj?:VavData):VavData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VavData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

airflow():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

damper():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startVavData(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addAirflow(builder:flatbuffers.Builder, airflow:number) {
  builder.addFieldFloat32(1, airflow, 0.0);
}

static addDamper(builder:flatbuffers.Builder, damper:number) {
  builder.addFieldFloat32(2, damper, 0.0);
}

static endVavData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVavData(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, airflow:number, damper:number):flatbuffers.Offset {
  VavData.startVavData(builder);
  VavData.addId(builder, idOffset);
  VavData.addAirflow(builder, airflow);
  VavData.addDamper(builder, damper);
  return VavData.endVavData(builder);
}
}
