// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Telemetry

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VavData struct {
	_tab flatbuffers.Table
}

func GetRootAsVavData(buf []byte, offset flatbuffers.UOffsetT) *VavData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VavData{}
	x.Init(buf, n+offset)
	return x
}

func FinishVavDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVavData(buf []byte, offset flatbuffers.UOffsetT) *VavData {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VavData{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVavDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VavData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VavData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VavData) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *VavData) Airflow() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *VavData) MutateAirflow(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *VavData) Damper() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *VavData) MutateDamper(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func VavDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func VavDataAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func VavDataAddAirflow(builder *flatbuffers.Builder, airflow float32) {
	builder.PrependFloat32Slot(1, airflow, 0.0)
}
func VavDataAddDamper(builder *flatbuffers.Builder, damper float32) {
	builder.PrependFloat32Slot(2, damper, 0.0)
}
func VavDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
