// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ZoneData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ZoneData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsZoneData(bb:flatbuffers.ByteBuffer, obj?:ZoneData):ZoneData {
  return (obj || new ZoneData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsZoneData(bb:flatbuffers.ByteBuffer, obj?:ZoneData):ZoneData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ZoneData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

temp():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

occupants():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

load():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startZoneData(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addTemp(builder:flatbuffers.Builder, temp:number) {
  builder.addFieldFloat32(1, temp, 0.0);
}

static addOccupants(builder:flatbuffers.Builder, occupants:number) {
  builder.addFieldInt32(2, occupants, 0);
}

static addLoad(builder:flatbuffers.Builder, load:number) {
  builder.addFieldFloat32(3, load, 0.0);
}

static endZoneData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createZoneData(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, temp:number, occupants:number, load:number):flatbuffers.Offset {
  ZoneData.startZoneData(builder);
  ZoneData.addId(builder, idOffset);
  ZoneData.addTemp(builder, temp);
  ZoneData.addOccupants(builder, occupants);
  ZoneData.addLoad(builder, load);
  return ZoneData.endZoneData(builder);
}
}
